version: '3'
services:
    message-store:
        image: postgres:13
        container_name: cpas-stub-db
        environment:
          - POSTGRES_USER=${postgres_user}
          - POSTGRES_PASSWORD=${postgres_password}
          - POSTGRES_DB=${postgres_db_name}
        ports:
        - 5432:5432
    cpas-server:
        depends_on:
        - message-store
        image: davisruk/cpas-stub:${app_version}-SNAPSHOT
        container_name: cpas-stub-container
        ports:
          - 9803:${server_receive_port}
          - 9804:${server_send_port}
          - 8080:8080
        environment:
            - tcp_send_port=${server_send_port}
            - tcp_receive_port=${server_receive_port}
            - database.service=cpas-stub-db
            - database.name=msgstore
            - spring.datasource.username=${postgres_user}
            - spring.datasource.password=${postgres_password}